// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"cyber-docker/internal/mods"
	"cyber-docker/internal/mods/docker"
	"cyber-docker/internal/mods/docker/api"
	"cyber-docker/pkg/container/di"
)

// Injectors from wire.go:

func BuildInjector(dic *di.Container) (*Injector, error) {
	client := GetDockerClient(dic)
	images := api.Images{
		Client: client,
	}
	dockerDocker := &docker.Docker{
		ImageApi: images,
	}
	modsMods := &mods.Mods{
		Docker: dockerDocker,
	}
	injector := &Injector{
		Mods:   modsMods,
		Client: client,
	}
	return injector, nil
}
